project_identifier: test
api_key: KeepTheAPIkeySecret
base_url: https://api.crowdin.com
base_path: /path/to/your/project
preserve_hierarchy: true

files:
  -
    source: '/**/*.*'
    translation: '/locale/%two_letters_code%/**/%original_file_name%'
    ignore: '/**/*.md'
